spring:
  profiles:
    active: dev
  application:
    name: auth-demo

---
server:
#  tomcat:
#    uri-encoding: UTF-8
  port: 8083
  servlet:
    context-path: /auth/v1

---
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/views/

---
jwtp:
  store-type: 1
  path: /auth/v1/test
  exclude-path: /login,/swagger-ui.html/**,/swagger-resources/**,/webjars/**,/v3/**,/swagger-ui.html#!/**,/csrf,/error,/v3/api-docs,/swagger-ui/index.html
  max-token: 1

---
# 分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=sountSql
  page-size-zero: true
---
# swagger3配置
springfox:
  documentation:
    swagger-ui:
      enabled: true