---
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test_job?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

---
# mybatis
mybatis:
  # 注意通配符的配置
  mapper-locations: classpath*:/mapper/**/**.xml
  # 实体扫描，mybatis 驼峰命名映射
  typeAliasesPackage: com.algebra.authentication.entity.domain
