spring:
  profiles:
    active: dev
  application:
    name: auth-demo

---
server:
#  tomcat:
#    uri-encoding: UTF-8
  port: 8083
  servlet:
    context-path: /auth/v1

---
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/views/

---
jwtp:
  store-type: 1
  path: /**
  exclude-path: /login,/swagger-ui.html/**,/swagger-resources/**,/webjars/**,/v2/**,/swagger-ui.html#!/**,/csrf,/error
  max-token: 1

---
logging:
  level:
    org.wf.jwtp.TokenInterceptor.preHandle: DEBUG