# mybatis
mybatis:
  # 注意通配符的配置
  mapper-locations: classpath*:/mapper/**/**.xml
  # 实体扫描，mybatis 驼峰命名映射
  typeAliasesPackage: com.algebra.demofastdep.entity.domain
# 分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=sountSql
  page-size-zero: true

fastdep:
  file:
    originName: true
    scheme: http
    uploadDir: "/{yyyy}/{MM}/{dd}"

  shiro-jwt:
    filter:
      admin:
        path: /admin/**
        role: jwt
      front:
        path: /front/**/**
        role: anon
    secret: "6Dx8SIuaHXJYnpsG18SSpjPs50lZcT52"

  datasource:
    master: #数据源名称可随意取
      mapper: com.algebra.demofastdep.mapper.master #当前数据源对应的mapper目录不能多个数据源相同
      password: 123456
      url: jdbc:mysql://127.0.0.1:3306/test_job?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
      driverClassName: com.mysql.jdbc.Driver
      username: root
      # 下面为连接池的补充设置
      # 初始化大小，最小，最大
      initialSize: 10
      minIdle: 5
      maxActive: 100
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      #      minEvictableIdleTimeMillis: 30
      minEvictableIdleTimeMillis: 300000
      maxEvictableIdleTimeMillis: 600000
      validationQuery: SELECT 1
      validationQueryTimeout: 10000
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      connectionInitSqls: 'set names utf8mb4;'

    slave: #数据源名称可随意取
      mapper: com.algebra.demofastdep.mapper.slave #当前数据源对应的mapper目录不能多个数据源相同
      password: 123456
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
      driverClassName: com.mysql.jdbc.Driver
      username: root
      # 下面为连接池的补充设置
      # 初始化大小，最小，最大
      initialSize: 10
      minIdle: 5
      maxActive: 100
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      #      minEvictableIdleTimeMillis: 30
      minEvictableIdleTimeMillis: 300000
      maxEvictableIdleTimeMillis: 600000
      validationQuery: SELECT 1
      validationQueryTimeout: 10000
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      connectionInitSqls: 'set names utf8mb4;'
  redis:
    redis1:
      database: 9
      host: 192.168.6.62
      port: 6379
      lettuce: #下面为连接池的补充设置
        shutdown-timeout: 100 # 关闭超时时间
        pool:
          max-active: 18 # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 8 # 连接池中的最大空闲连接
          max-wait: 30 # 连接池最大阻塞等待时间（使用负值表示没有限制）
          min-idle: 0 # 连接池中的最小空闲连接
    redis2:
      database: 9
      host: 192.168.6.63
      port: 6379
      lettuce: #下面为连接池的补充设置
        shutdown-timeout: 100 # 关闭超时时间
        pool:
          max-active: 18 # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 8 # 连接池中的最大空闲连接
          max-wait: 30 # 连接池最大阻塞等待时间（使用负值表示没有限制）
          min-idle: 0 # 连接池中的最小空闲连接