spring:
  application:
    name: sys-test
  profiles:
    active: dev
  config:
    import: optional:consul:localhost:8500
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      config:
        acl-token: 9cd9d389-a8e6-5510-7f54-e350cf65c6c8
        # \u9ED8\u8BA4\u662Ftrue
        enabled: true
        # \u8868\u793Aconsul\u4E0A\u9762\u6587\u4EF6\u7684\u683C\u5F0F\uFF0C\u6709\u56DB\u79CD\uFF1A YAML PROPERTIES KEY-VALUE FILES
        format: yaml
        # \u8868\u793A\u6700\u540E\u4E00\u5C42\u8282\u70B9\u7684key\u503C\u540D\u79F0 \u9ED8\u8BA4\u662Fdata
        data-key: data
        # \u8868\u793Aconsul\u7528\u4E8E\u5B58\u50A8\u914D\u7F6E\u7684\u6587\u4EF6\u5939\u6839\u76EE\u5F55\u540D\u4E3Aconfig
        prefixes:
          - config
        #  \u8868\u793A\u914D\u7F6E\u6587\u4EF6\u5BF9\u5E94\u7684\u5E94\u7528\u540D\u79F0
        default-context: application
        # \u8868\u793A\u5982\u679C\u6709\u591A\u4E2Aprofile(eg: \u5F00\u53D1\u73AF\u5883dev\uFF0C\u6D4B\u8BD5\u73AF\u5883test...) \uFF0C\u5219key\u540D\u4E2D\u7684profile\u4E0EdefaultContext\u4E4B\u95F4\uFF0C\u7528\u4EC0\u4E48\u5206\u9694\u7B26\u6765\u8868
        profile-separator: ','
      discovery:
        # \u662F\u5426\u9700\u8981\u6CE8\u518C
        enabled: true
        tags:
          - version=1.0
          - author=algebra
        # \u670D\u52A1\u540D\u79F0
        service-name: ${spring.application.name}
        # \u6CE8\u518C\u5B9E\u4F8BID\uFF0C\u5FC5\u987B\u552F\u4E00
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}
        # \u5065\u5EB7\u68C0\u67E5
        health-check-path: /demo/actuator/health
        health-check-interval: 5s
        # \u662F\u5426\u4F7F\u7528IP\u5730\u5740\u6CE8\u518C
        prefer-ip-address: true
        # \u5F53\u524D\u5B9E\u4F8B\u8BF7\u6C42IP
        ip-address: ${spring.cloud.client.ip-address}
        acl-token: e6d2d573-e88c-d157-32db-87f4a73ed753
#        heartbeat:
#          enabled: false
        # \u914D\u7F6E\u57DF\u540D\u8BBF\u95EE
#        hostname: algebra
#        register: false
#        deregister: false
#        register-health-check: false

# \u7AEF\u53E3\u53F7\u548C\u8BBF\u95EE\u8DEF\u5F84
server:
  port: 8080
  servlet:
    context-path: /demo

# \u5065\u5EB7\u68C0\u67E5
management:
  endpoint:
    health:
      show-details: always

#person:
#  login:
#    username: tom
#    aclToken: asdas14245asd