spring:
  application:
    name: sys-test
  profiles:
    active: dev
  config:
    import: optional:consul:10.11.2.62:8500
  cloud:
    consul:
      host: 10.11.2.62
      port: 8500
      config:
        acl-token: a37e739e-cf8d-05c3-8939-3d9911464129
        # 默认是true
        enabled: true
        # 表示consul上面文件的格式，有四种： YAML PROPERTIES KEY-VALUE FILES
        format: yaml
        # 表示最后一层节点的key值名称 默认是data
        data-key: data
        # 表示consul用于存储配置的文件夹根目录名为config
        prefixes:
          - config
        #  表示配置文件对应的应用名称
        default-context: application
        # 表示如果有多个profile(eg: 开发环境dev，测试环境test...) ，则key名中的profile与defaultContext之间，用什么分隔符来表
        profile-separator: '-'
      discovery:
        # 是否需要注册
        enabled: true
        tags:
          - version=1.0
          - author=algebra
        # 服务名称
        service-name: ${spring.application.name}
        # 注册实例ID，必须唯一
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}
        # 健康检查
        health-check-path: /actuator/health
        health-check-interval: 5s
        # 是否使用IP地址注册
        prefer-ip-address: true
        # 当前实例请求IP（这个IP有讲究）
        ip-address: 10.11.2.56
        acl-token: a37e739e-cf8d-05c3-8939-3d9911464129
#        heartbeat:
#          enabled: false
        # 配置域名访问
#        hostname: algebra
#        register: false
#        deregister: false
#        register-health-check: false

# 端口号和访问路径
server:
  port: 8881
  servlet:
    context-path: /

# 健康检查
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

hystrix:
  dashboard:
    proxy-stream-allow-list:
      - 10.11.2.56
