spring:
  application:
    name: sys-test
  profiles:
    active: dev
  config:
    import: optional:consul:localhost:8500
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        # \u9ED8\u8BA4\u662Ftrue
        enabled: true
        # \u8868\u793Aconsul\u4E0A\u9762\u6587\u4EF6\u7684\u683C\u5F0F\uFF0C\u6709\u56DB\u79CD\uFF1A YAML PROPERTIES KEY-VALUE FILES
        format: yaml
        # \u8868\u793A\u6700\u540E\u4E00\u5C42\u8282\u70B9\u7684key\u503C\u540D\u79F0 \u9ED8\u8BA4\u662Fdata
        data-key: data
        # \u8868\u793Aconsul\u7528\u4E8E\u5B58\u50A8\u914D\u7F6E\u7684\u6587\u4EF6\u5939\u6839\u76EE\u5F55\u540D\u4E3Aconfig
        prefixes:
          - config
        #  \u8868\u793A\u914D\u7F6E\u6587\u4EF6\u5BF9\u5E94\u7684\u5E94\u7528\u540D\u79F0
        default-context: application
        # \u8868\u793A\u5982\u679C\u6709\u591A\u4E2Aprofile(eg: \u5F00\u53D1\u73AF\u5883dev\uFF0C\u6D4B\u8BD5\u73AF\u5883test...) \uFF0C\u5219key\u540D\u4E2D\u7684profile\u4E0EdefaultContext\u4E4B\u95F4\uFF0C\u7528\u4EC0\u4E48\u5206\u9694\u7B26\u6765\u8868
        profile-separator: ','
      discovery:
        service-name: ${spring.application.name}
        enabled: true
#        prefer-ip-address: true
#        heartbeat:
#          enabled: false
#        deregister: false
#        register-health-check: false
#        acl-token: 1111
#        register: false

# \u7AEF\u53E3\u53F7\u548C\u8BBF\u95EE\u8DEF\u5F84
server:
  port: 8080
  servlet:
    context-path: /

# \u5065\u5EB7\u68C0\u67E5
management:
  endpoint:
    health:
      show-details: always