spring:
  application:
    name: sys-gateway
  profiles:
    active: dev
  config:
    location: 10.11.2.62
  cloud:
    gateway:
      discovery:
        locator:
          # \u542F\u7528\u672C\u5730\u5316\u7F51\u5173
          enabled: true
          # \u5C06\u670D\u52A1\u540D\u8F6C\u6362\u4E3A\u5C0F\u5199
          #lower-case-service-id: true
    # consul
    consul:
      host: 10.11.2.62
      port: 8500
      # consul-config
      config:
        enabled: false
        acl-token: a37e739e-cf8d-05c3-8939-3d9911464129
        format: yaml
        data-key: data
        prefix: config
        default-context: application
        profile-separator: '-'
      # consul-discovery
      discovery:
        enabled: true
        acl-token: a37e739e-cf8d-05c3-8939-3d9911464129
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}
        health-check-interval: 10s
        prefer-ip-address: true
        ip-address: 10.11.2.56
        tags: version=1.0, author=algebra

# \u7AEF\u53E3\u53F7\u548C\u8BBF\u95EE\u8DEF\u5F84
server:
  port: 8880
  servlet:
    context-path: /

# \u5065\u5EB7\u68C0\u67E5
management:
  endpoint:
    health:
      show-details: always
