spring:
  application:
    name: algebra-demo
  profiles:
    include: param
    active: dev

---
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8082
  servlet:
    context-path: /base/v1

---
spring:
  thymeleaf:
    cache: false #关闭页面缓存
    prefix: classpath:/views/ #页面拼接路径
  messages:
    basename: i18n/messages #相对路径 首部请勿添加斜杠