---
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test_job?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: algebra
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

---
# 普通redis配置
spring:
  redis:
    database: 0
    host: 49.233.146.198
    port: 6379
    password:
    jedis:
      pool:
        # 连接池最大连接数（负数表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间
        max-wait: -1
        # 连接池最大/最小空闲时间
        max-idle: 10
        min-idle: 0
    #链接超时时间
    timeout: 1000

---
# mybatis
mybatis:
  # 注意通配符的配置
  mapper-locations: classpath*:/mapper/**/**.xml
  # 实体扫描，mybatis 驼峰命名映射
  typeAliasesPackage: com.algebra.demobase.entity.domain
# 分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=sountSql
  page-size-zero: true

