spring:
  application:
    name: shard-demo
  profiles:
#    include: data
    active: shard2

---
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8085
  servlet:
    context-path: /shard/v1

# mybatis
mybatis:
  # 注意通配符的配置
  mapper-locations: classpath*:/mapper/**/**.xml
  # 实体扫描，mybatis 驼峰命名映射
  typeAliasesPackage: com.algebra.demoshard.entity.domain
# 分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=sountSql
  page-size-zero: true
spring:
  main:
    allow-bean-definition-overriding: true
