# sharding 单库分表
sharding:
  jdbc:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
        username: root
        password: 123456
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/test_job?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
        username: root
        password: 123456
    config:
      sharding:
        tables:
          t_user:
            actual-data-nodes: ds${0..1}.t_user_${0..1}
            databaseStrategy:
              inline:
                shardingColumn: city_id
                algorithmExpression: ds${city_id % 2}
            table-strategy:
              inline:
                sharding-column: city_id
                algorithm-expression: t_user_${city_id % 2}
            keyGenerator:
              type: SNOWFLAKE
              column: id
        binding-tables:
          - t_user
        default-data-source-name: ds0
      props:
        sql.show: true